type: internal_cloud

# Common
environment:
  type: internal
control_plane_api:
  endpoint: data-transfer.yandex-team.ru:8443
  plaintext: false
log:
  type: stdout
profiler:
  type: disabled
pg_dump_command: ["pg_dump"]
clickhouse_local: "clickhouse"
metering:
  type: disabled

# Cloud
cloud_creds:
  type: passport_oauth_token
  token:
    type: yav
    secret_id: sec-01ddj4pn4eg5hmyd3kjkczhm0w
    version: ver-01fg9r96zjq7hzyzs2bvx1xnj4
    key: CDC_DBAAS_TOKEN
root_cert_paths:
  - /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt
mdb_api_url_base: https://gw.db.yandex-team.ru/
cloud_api_endpoint: gw.db.yandex-team.ru:443
iam_api_url_base: https://gw.db.yandex-team.ru:443/iam/v1/
logbroker_token:
  type: yav
  secret_id: sec-01dpnps7g3jkwwsfhzvdm2ybw4
  version: ver-01dpnps7ggve70nrybv5ap5taw
  key: lb

# Internal cloud
solomon_token:
  type: yav
  secret_id: sec-01dpnps7g3jkwwsfhzvdm2ybw4
  version: ver-01eewths5arkqh0k8d0pnan8vx
  key: solomon
ydb_token:
  type: yav
  secret_id: sec-01dpnps7g3jkwwsfhzvdm2ybw4
  version: ver-01e5wrf991geg3h02pe4n2fcv4
  key: ydb
yt_token:
  type: yav
  secret_id: sec-01dpnps7g3jkwwsfhzvdm2ybw4
  version: ver-01f8t8hy3699hrb2050s680gbt
  key: yt
dataplane_token:
  type: yav
  secret_id: sec-01ddj4pn4eg5hmyd3kjkczhm0w
  version: ver-01fg9r96zjq7hzyzs2bvx1xnj4
  key: CDC_DBAAS_TOKEN
logfeller_yt_token:
  type: yav
  secret_id: sec-01e4xz5vc007whwy8pvax96bz2
  version: ver-01fxsne874kxnvaj19y2x6be32
  key: nirvana-secret
logfeller_nirvactor_token:
  type: yav
  secret_id: sec-01e4xzjqs0a61e3y576ek5c7zw
  version: ver-01fxstmtn3mvyyamy050xfkbg5
  key: nirvana-secret
logfeller_logbroker_token:
  type: yav
  secret_id: sec-01gdn7wkcgc3awnvvtxcpk7rkw
  version: ver-01gdn7wkcse36m7xk4xsr99czv
  key: logbroker-token
logfeller_lf_describer_logbroker_token:
  type: yav
  secret_id: sec-01h4k2mwcva6xq9w5p90kkwnpc
  version: ver-01h52qv834xj62dvmbfsx1d3f6
  key: logbroker-oauth-token
mdb_token:
  type: yav
  secret_id: sec-01ddj4pn4eg5hmyd3kjkczhm0w
  version: ver-01fg9r96zjq7hzyzs2bvx1xnj4
  key: CDC_DBAAS_TOKEN
solomon_cluster: rtc-prod
yt_proxy: vanga
ydb_instance: ydb-ru.yandex.net:2135
ydb_tracker_database: /ru/transfer_manager/prod/data-transfer-yt
udf_dir: ./
yav_token:
  type: environment_variable
  variable_name: YAV_TOKEN
