type: internal_cloud

# Common
environment:
  type: internal
db_discovery:
  type: mdb
  cluster_id: mdbn9rt3ij3n0p93r701
db_user: db_user
db_password:
  type: yav
  secret_id: sec-01dpnps7g3jkwwsfhzvdm2ybw4
  version: ver-01f7bvkkt4cgckdd6t72wmerdf
  key: db_password
db_name: db
db_schema: public
disable_dataplane: false
grpc_port: 8787
public_grpc_port: 9797
rest_port: 80
exported_metrics_http_port: 9092
log:
  type: logbroker
  endpoint: logbroker.yandex.net
  creds:
    type: oauth_token
    token:
      type: yav
      secret_id: sec-01dpnps7g3jkwwsfhzvdm2ybw4
      version: ver-01dpnps7ggve70nrybv5ap5taw
      key: lb
  database: ''
  topic: /cdc/prod/control-plane/log
  tls_mode:
    type: disabled
  use_topic_api: false
skip_auth: false
push_metrics: true
profiler:
  type: logbroker
  endpoint: logbroker.yandex.net
  creds:
    type: oauth_token
    token:
      type: yav
      secret_id: sec-01dpnps7g3jkwwsfhzvdm2ybw4
      version: ver-01dpnps7ggve70nrybv5ap5taw
      key: lb
  database: ''
  topic: cdc/prod/profiler
  tls_mode:
    type: disabled
  use_topic_api: false

# Cloud
solomon_token:
  type: yav
  secret_id: sec-01dpnps7g3jkwwsfhzvdm2ybw4
  version: ver-01eewths5arkqh0k8d0pnan8vx
  key: solomon
logbroker_token:
  type: yav
  secret_id: sec-01dpnps7g3jkwwsfhzvdm2ybw4
  version: ver-01dpnps7ggve70nrybv5ap5taw
  key: lb
cloud_creds:
  type: passport_oauth_token
  token:
    type: yav
    secret_id: sec-01ddj4pn4eg5hmyd3kjkczhm0w
    version: ver-01fg9r96zjq7hzyzs2bvx1xnj4
    key: CDC_DBAAS_TOKEN
console_hostname: yc.yandex-team.ru
ydb_logs_instance: ydb-ru.yandex.net:2135
ydb_logs_database: /ru/transfer_manager/prod/data-transfer-yt
root_cert_paths:
  - /usr/local/share/ca-certificates/YandexInternalRootCA.crt
ydb_dataplane_log_dir: /ru/transfer_manager/prod/data-transfer-yt/log/dataplane
mdb_api_url_base: https://gw.db.yandex-team.ru/
iam_api_url_base: https://gw.db.yandex-team.ru/iam/v1/
cloud_api_endpoint: gw.db.yandex-team.ru:443
iam_access_service_endpoint: as.cloud.yandex-team.ru:4286
events:
  type: disabled
dataplane_version:
  type: from_database
health_providers:
#  - type: solomon TODO: decide whether this alert should be fixed or dropped
#    alert_id: 7fd353ed-025a-4a9d-8e48-3be6a300e96f
#    name: dta_01_dataplane_is_alive
  - type: solomon
    alert_id: b806e979-48e7-4faf-8876-0e92148c71b7
    name: dta_02_no_items_in_memory
  - type: solomon
    alert_id: bb31436f-11be-4264-a873-59f67b39ae23
    name: dta_03_transfer_time_sound
  - type: solomon
    alert_id: 0f149b88-1662-40a6-b34d-fc6856c728e2
    name: dta_04_row_max_lag_constant
  - type: solomon
    alert_id: data-transfer_dta_05_replication_restarts
    name: dta_05_replication_restarts
  - type: status_message
  - type: operation_status
metrics_provider:
  type: solomon
search:
  type: disabled
s3_endpoint: https://s3.mds.yandex.net
s3_region: ru-central1

# Internal cloud
ydb_token:
  type: yav
  secret_id: sec-01dpnps7g3jkwwsfhzvdm2ybw4
  version: ver-01e5wrf991geg3h02pe4n2fcv4
  key: ydb
mdb_token:
  type: yav
  secret_id: sec-01ddj4pn4eg5hmyd3kjkczhm0w
  version: ver-01fg9r96zjq7hzyzs2bvx1xnj4
  key: CDC_DBAAS_TOKEN
yav_token:
  type: environment_variable
  variable_name: YAV_TOKEN
yt_token:
  type: yav
  secret_id: sec-01dpnps7g3jkwwsfhzvdm2ybw4
  version: ver-01f8t8hy3699hrb2050s680gbt
  key: yt
logfeller_yt_token:
  type: yav
  secret_id: sec-01e4xz5vc007whwy8pvax96bz2
  version: ver-01fxsne874kxnvaj19y2x6be32
  key: nirvana-secret
logfeller_nirvactor_token:
  type: yav
  secret_id: sec-01e4xzjqs0a61e3y576ek5c7zw
  version: ver-01fxstmtn3mvyyamy050xfkbg5
  key: nirvana-secret
logfeller_logbroker_token:
  type: yav
  secret_id: sec-01gdn7wkcgc3awnvvtxcpk7rkw
  version: ver-01gdn7wkcse36m7xk4xsr99czv
  key: logbroker-token
logfeller_lf_describer_logbroker_token:
  type: yav
  secret_id: sec-01h4k2mwcva6xq9w5p90kkwnpc
  version: ver-01h52qv834xj62dvmbfsx1d3f6
  key: logbroker-oauth-token
tls_server_private_certificate:
  type: yav
  secret_id: sec-01hzh7xb2s83m03ydhndm6qmhk
  version: ver-01hzh7xb45rwavz8npkmpkd88a
  key: 7F002F06818CD05B3D1129DACF0002002F0681_key_cert
dataplane_token:
  type: yav
  secret_id: sec-01ddj4pn4eg5hmyd3kjkczhm0w
  version: ver-01fg9r96zjq7hzyzs2bvx1xnj4
  key: CDC_DBAAS_TOKEN
solomon_cluster: rtc-prod
grpc_ssl_port: 8443
public_grpc_ssl_port: 9443
yt_proxy: vanga
yt_operation_pool: transfer_manager
udf_dir: /usr/local/bin/udfs
data_plane_config_variable_name: DATA_PLANE_CONFIG_RESOURCE
data_plane_config_variable_value: internal_prod.yaml
task_monitor_lock_path: //home/transfer-manager/task_monitor/internal_prod.yaml
notifications_api: https://notify.cloud.yandex-team.ru/v2/send
solomon_url: https://solomon.yandex-team.ru
solomon_project: data-transfer
dataplane_image_k8s_image: '' # TODO: move this into the dataplane_stage_versions table in postgres
