type: external_cloud

# Common
environment:
  type: yc
control_plane_api:
  endpoint: tm.private-api.ycp.cloud-preprod.yandex.net:443
  plaintext: false
log:
  type: stdout
profiler:
  type: disabled
pg_dump_command: ["pg_dump"]
clickhouse_local: "clickhouse"
metering:
  type: disabled

# Cloud
cloud_creds:
  type: service_account_key
  id: bfb1t32ubmouil47690i
  service_account_id: bfbgnr9a209qmtjepb55
  key_algorithm: RSA_2048
  private_key:
    type: yav
    secret_id: sec-01f7rct6h4zm2m22kcas8k7zxg
    version: ver-01f7rct6hk6xsenwnzjxympvwy
    key: preprod
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoaEfA9epQ0AN4xOkhxok
    s7TexwJ3diDuD54A9Z1zJRI55/yLFcd0Eb9V2MC/MEfRRoO/UJovXyW7X9fufuYJ
    IWWsHm0TtkQ6EINE6MnKTtaUOBhlczq3kRbn+aU0svL6sqxe2Wxejus8ExKtS9o6
    OPEE5W7U4qGdLr8RhsGUFq5WyVrU/6DYN5HYTZV4JR3zyVQP6ZQIYyPg+F8ebwyA
    yq+3420Db6LK2LsQEo/ui5huYHFdBqwE2P7g/gW9mBM2NcE9rA689TnRlhpK+hGp
    tVzRSrtqN26mRCdVsVgDcEKKbrdtw6L7YmwfeUaOYt7RNPh2CnopH22Lw55t+6LH
    uQIDAQAB
    -----END PUBLIC KEY-----
root_cert_paths:
  - /usr/local/share/ca-certificates/YandexInternalRootCA.crt
mdb_api_url_base: https://mdb.api.cloud-preprod.yandex.net/
cloud_api_endpoint: api.cloud-preprod.yandex.net:443

# External cloud
service_cloud_id: aoerc1it1q975rso0ia8
service_folder_id: aoenp6537r7gn90vb4al
solomon_url: https://solomon.cloud-preprod.yandex-team.ru
cloud_functions_base_url: https://functions.cloud-preprod.yandex.net
kms_key_id: e10jg948rdlerghctsv3
kms_discovery_endpoint: kms.cloud-preprod.yandex.net:8443
yds_serverless_endpoint: yds.serverless.cloud-preprod.yandex.net
yav_token:
  type: environment_variable
  variable_name: YAV_TOKEN
metrika:
  type: disabled
