type: aws
environment:
  type: aws

dataplane_sa:
  id: yc.data-transfer.agent
  folder_id: yc.data-transfer.service
assume_role_target: arn:aws:iam::221736954043:role/data-transfer-mdb-cp
iam:
  access_service: prod.iam.internal.double.tech:4286
  token_service: prod.iam.internal.double.tech:4282
  private_service: prod.iam.internal.double.tech:4283
mdb_service: prod.mdb.internal.double.tech:443
mdb_vpc_service: vpc.prod.mdb.internal.double.tech:443
cloud_creds:
  type: service_account_key
  id: yc.data-transfer.agent
  service_account_id: yc.data-transfer.agent
  key_algorithm: RSA_4096
  private_key:
    type: aws_secret_manager
    secret_id: arn:aws:secretsmanager:eu-central-1:179772598917:secret:control-plane
    key: sa_private_key
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAzopUsI5QVhGP5Um+dvu6
    B5b8zIHpye4OLQNu/PkL6aG90I+WB/gb728QMJ9aLW8OCLXmAN7vqsHARceqiYyn
    BwlLb5wWUve0iJoJnMbRPxiP0sgzRs/h39ugLqd54b8xnAa9I0N/wPizjqRQN1vJ
    ulSArU1uqy4xTIObaRwWU4j3y/Cd3JvMbka8mTSS7BLlRadlkAWcD7on6mz9BX6O
    19K1E0SjqM1EzCVTP1aH2j2NTKI67cQabDr/QpVg5t1xG2zto/hbXFlMIv6DPvJl
    R3gvlDAHtJfrIwCr9lcipsyGaVoOC2calcG2U0byh0UYN8gRRRybp9bWyoANmsO9
    DtQlfIH0Hya5kB75mAHiPUzYPKUR/YkT8RiaR5yqWFZdoSrU77GR7J+gxcxHzBGd
    fMXGZIKZoMhb23Hl8GQ+Ne3/jqoXKvkzTOiLDCUKVdSd335RvbzuiJQKL7eYRtIL
    JHgwVSHXmYY0Tei2ImimdrpnTmvdXaqjEj5w0F7QH9X81/HQ234pTg7K4VYKZNIM
    encsvOKKWMZjHM21f6lc8qpxJtF4D1Ap+mc3xhfXb0L/68XO9rZCtLtD8mhB3g3W
    0KgoZ6J6SmZ49+suoYPQFKrJ23MuwJlIqKs44Dmu7i0aXrAmvVIqyJJuJQpBtBTp
    p9rhVIMgEUbfbCUYw3P/DrMCAwEAAQ==
    -----END PUBLIC KEY-----
key_id: 'arn:aws:kms:eu-central-1:179772598917:alias/data-transfer-master-key'
ami_config:
  instance_profile: data-transfer-mdb-dp
  region_to_ami: # Dataplane EC2 AMI per-region
    ap-northeast-1: ami-070346bc4332d6617
    ap-northeast-2: ami-07b5fdb007f8f458e
    ap-northeast-3: ami-033217334260bc303
    ap-south-1: ami-0737b8a3dd101d1e5
    ap-southeast-1: ami-0e0e7ddb545281179
    ap-southeast-2: ami-0a270c95e7a438e99
    ca-central-1: ami-0f2092fdc6a5826b7
    eu-central-1: ami-0302d08fed620a271
    eu-north-1: ami-09fcf05651153a2d0
    eu-west-1: ami-0d8eb723c4bc8b934
    eu-west-2: ami-092a18752a42c6f34
    eu-west-3: ami-0711782f579d0e127
    me-south-1: ami-0906566801c3e31ce
    sa-east-1: ami-0f5029b9f41ed8b8f
    us-east-1: ami-0667f03604b4770ae
    us-east-2: ami-01ef4edfab5cdafa7
    us-west-2: ami-046aac667d1b30c7b
dataplanes: # named list of kubeconfig-s
  - name: eks_data-transfer-dp-frankfurt # default data plane k8s cluster
    region: 'eu-central-1'
    secret: |
      apiVersion: v1
      preferences: {}
      kind: Config

      clusters:
      - cluster:
          server: https://46F0394EC1704FD4508EDFC2BEFCFC38.yl4.eu-central-1.eks.amazonaws.com
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EVXdOVEV6TXpJek1Wb1hEVE15TURVd01qRXpNekl6TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1ZQCnBuZkZRN29PKzRpWTNEWkJtUUJpUjZWS2lUQm5oS3lXc2NBejBFRCtDNG16YmlqNW1pRmxZSDl3bWM2QzRZek8KMDVJVmxKQktyMFFNb0ZwMDR2RFFJcjFubDIyd2REbjBQTkxqM3I5YnNyc1dLMlV6OEU1S2RzZjdvajBTUlV3TApkMUJMQmIwaitVUFhJeGE2UytoYWFMRjYxZDhvVHQ2SFF3NFl6ZEY5S0hYZHhyb2NOb2srME5uTUx2S1d1dlczCkFyTnZGOGFNSzZvK3pnbFlYMmN5T3BCeEdESnJQQkljalBQejlSK25wbEtrQU83elZKRTJ1K2xiUEd6OEl0dzMKckFQTnVZL2FRMXV2MFhhQXlxTm9LWWNVL09UV2dHNWFiRVVuSTZnUjZyMmFIQU5wdWliaFVabHBpRHNoejMybQo5S1lOd0N6UTBzdG9jT2dSTzZjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJQk91MGNrUUZKdE11bXlseXJ2bzlxREZyd0dNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS0wyb0R2eEFGSlZVb1hvNnpEUwo1ejY0TGYzcnRwK2hTS3dVSUlENWRLRDI2UkhMUTZoUTNMYjlIdWgxVDBhUlFtMlFEMnVLTDhPMXl1ZytoYUpPClhPWXI0NVNsRERMeU5qSEdyNUU2bUtnNW9naUJrajdoOVhlMVkwUkdGLytPQXdUUnA0MEZYcnIyRURVK3M4VisKTHVDWkFSdExyUXM1bm5XcGJwNHA3U2Nxa2FYZkZ6cWFVYk4xeDRjVG1GUUNmZjVocXNueEk5K3BmdWFxcjcrTgp6NlRPazh0c1U3UVRPNDV0aFJyUVZseWpNNFIxb214U1pqTGtEcm02MUF1NkVYQ05SRVNNamdpR3Q0b2ZYMHlmClV0Y0ZWUFRGeGpFNW1aNWhQeTROVVlTQ1NXbDQvc1NsYlhCSCtxcW5nbUVNTWFSNUxReVlaOHdIUktCS08xdWsKdjE4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        name: data-transfer-dp-frankfurt-ipv6

      contexts:
      - context:
          cluster: data-transfer-dp-frankfurt-ipv6
          user: data-transfer-dp-frankfurt-ipv6
        name: data-transfer-dp-frankfurt-ipv6

      current-context: data-transfer-dp-frankfurt-ipv6

      users:
      - name: data-transfer-dp-frankfurt-ipv6
        user:
          exec:
            apiVersion: client.authentication.k8s.io/v1
            command: aws
            args:
              - --region
              - eu-central-1
              - eks
              - get-token
              - --cluster-name
              - "data-transfer-dp-frankfurt-ipv6"
            interactiveMode: IfAvailable

data_plane_config_variable_name: DATA_PLANE_CONFIG_RESOURCE
data_plane_config_variable_value: aws_prod.yaml
dataplane_spec_s3_bucket: "double-cloud-data-transfer-prod-specs"

dataplane_image_k8s_image:
  type: environment_variable
  variable_name: DATA_PLANE_K8S_IMAGE

notifications_api: 'https://notify.ui.internal.double.tech/v1/send'

# AWS-managed prometheus
amp_region: eu-central-1
amp_url: 'https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-a2ea1ab6-82a2-45a3-9bbd-5cff23d2a4e2/api/v1' #prod
amp_assume_role_target: 'arn:aws:iam::179772598917:role/cp-prom-reader' # prod role

clusters_cp_account_id: '883433064081'
cp_account_id: '179772598917'
dp_account_id: '221736954043'

teleport:
  type: enabled
  telepass_url: http://telepass.telepass:80/token
  proxy: doublecloud.teleport.sh:443
  labels:
    Infra: prod
    Team: data-transfer
    Plane: data
    Type: transfer

gcp:
  byoa_common_account: 'controlplane@byoa-doublecloud.iam.gserviceaccount.com'
  image_id: 'projects/mdb-dp-prod/global/images/dc-gcp-amd64-dt-20231117100928'
  project_id: 'mdb-dp-prod'
  service_account: 'common-dt-dp-sa@mdb-dp-prod.iam.gserviceaccount.com'
  creds: |
    {
      "type": "external_account",
      "audience": "//iam.googleapis.com/projects/113033745255/locations/global/workloadIdentityPools/mdb-dt/providers/dt-aws-179772598917",
      "subject_token_type": "urn:ietf:params:aws:token-type:aws4_request",
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/common-dt-dp-sa@mdb-dp-prod.iam.gserviceaccount.com:generateAccessToken",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "environment_id": "aws1",
        "region_url": "http://169.254.169.254/latest/meta-data/placement/availability-zone",
        "url": "http://169.254.169.254/latest/meta-data/iam/security-credentials",
        "regional_cred_verification_url": "https://sts.{region}.amazonaws.com?Action=GetCallerIdentity&Version=2011-06-15"
      }
    }
