include_configs:
  - type: resource
    name: dc_local.yaml


control_plane_api:
  # this is tunnel proxy to your local control plane, to get one run:
  # ktunnel expose tserakhau 80:8787 --context arn:aws:eks:eu-central-1:840525340941:cluster/data-transfer-preprod --namespace transfer-tserakhau --service-type LoadBalancer
  # see: https://github.com/omrikiei/ktunnel for more details
  endpoint: af045d99f7c9b4313b8d86d30ece3bf4-577419582.eu-central-1.elb.amazonaws.com:80
  plaintext: true
