# preprod config
type: aws

# Common
environment:
  type: aws
control_plane_api:
  endpoint: data-transfer.expose.bi.yadc.io:443
  plaintext: false
log:
  type: kafka
  topic: data-transfer-dp
  brokers: rw.kfch29rtrbmadvak798r.at.yadc.io:9091
  user: admin
  password:
    type: aws
    ciphertext: !!binary |
      AQICAHiTU+2rvUdiJjPm/+F92pYl7aZuIXUqp52TCfwucx3y6QHB7OSZ7R4JTOa3qEVMo/RvAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkcMRr2MtCL8rq8y+AgEQgCs404InZmSIxFEi8lAFrKhJ2ucGmYeK2LAS7mNCSLRSlRZH802Gv9hjRxTo
  tls_mode:
    type: disabled
profiler:
  type: disabled
pg_dump_command: ["/usr/bin/pg_dump"]
clickhouse_local: "clickhouse"
metering:
  type: disabled

# AWS
iam:
  access_service: ops.private-api.iam.internal.yadc.tech:4286
  token_service: ops.private-api.iam.internal.yadc.tech:4282
  private_service: ops.private-api.iam.internal.yadc.tech:4283
  org_service: preprod.iam.internal.yadc.tech:4290
mdb_service: mdb.expose.bi.yadc.io:443 # we proxy all mdb api calls to our control plane for extra security
cloud_creds:
  type: ycp_profile
  profile_name: doublecloud-aws-preprod
key_id: 'arn:aws:kms:eu-central-1:840525340941:key/c4b45158-9287-4187-bcff-7ace91df54d2'
root_cert_paths:
  -  '/usr/local/share/ca-certificates/letsencrypt-stage.crt'

# AWS-managed prometheus
amp_region: eu-central-1
amp_url: 'https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-195f8815-a36f-445e-aa51-7c9dd93e43b2/api/v1/remote_write' #preprod

assume_role_target:
  type: local_file
  file_path: /var/lib/data-transfer/override_assume_role_target
cp_account_id: '840525340941'

assume_role_target_chain:
  type: local_file # arn:aws:iam::221736954043:role/DoubleCloud/clusters/dataplane-node-ID_OF_INSTANCE
  file_path: /var/lib/data-transfer/assume_chain

public_container_registry_service: public.ecr.aws/t9p9v8b9
dbt_image_tag: "12226335.preprod"
