type: external_cloud

# Common
environment:
  type: yc
control_plane_api:
  endpoint: localhost:8787
  plaintext: true
log:
  type: stdout
profiler:
  type: disabled
pg_dump_command: ["/usr/bin/pg_dump"]
clickhouse_local: "clickhouse"
metering:
  type: disabled

# Cloud
cloud_creds:
  type: yc_profile
  profile_name: sa-tm-preprod
root_cert_paths:
  - /usr/local/share/ca-certificates/YandexInternalRootCA.crt
mdb_api_url_base: https://mdb.api.cloud-preprod.yandex.net/
cloud_api_endpoint: api.cloud-preprod.yandex.net:443
yav_token:
  type: environment_variable
  variable_name: YAV_TOKEN # Get your token at https://oauth.yandex-team.ru/authorize?response_type=token&client_id=ce68fbebc76c4ffda974049083729982

# External cloud
service_cloud_id: aoerc1it1q975rso0ia8
service_folder_id: aoenp6537r7gn90vb4al
solomon_url: https://solomon.cloud-preprod.yandex-team.ru
cloud_functions_base_url: https://functions.cloud-preprod.yandex.net
kms_key_id: e10jg948rdlerghctsv3
kms_discovery_endpoint: kms.cloud-preprod.yandex.net:8443
yds_serverless_endpoint: yds.serverless.cloud-preprod.yandex.net
metrika:
  type: enabled
  api:
    endpoint: internalapi.test.metrika.yandex.net
    tvm_metrika_id: 2000269
    tvm_self_id: 2038887
    tvm_secret:
      type: yav
      secret_id: sec-01ggw9b0pv6d6jzv99r3ttxbq4
      version: ver-01ggw9b0qsfcn20rxthh7yjnpk
      key: client_secret
  topics:
    endpoint: lb.etni26gr4a9ukhsl4isv.ydb.mdb.yandexcloud.net
    database: /global/b1g5mv5j313nt9j9irv2/etni26gr4a9ukhsl4isv
    iam_token_service_api: iam.api.cloud.yandex.net:443
    creds:
      type: service_account_key
      id: ajelb8n9ibt17hdff5f4
      service_account_id: ajej56e44j0jj112pdgh
      key_algorithm: RSA_2048
      private_key:
        type: yav
        secret_id: sec-01f7rct6h4zm2m22kcas8k7zxg
        version: ver-01gkrr7pswdseze58rrzecsqhq
        key: metrika-test-sa
      public_key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArr2b8wm8HtlOWdmTA2YK
        lMQa46ZcKew/z9VYsBsgrz5YOTHYX9KWr5ilCNz3dNh9MdsDZYNxmlcTX7FaLAUr
        2c8Dmp4s2fRur1XtqVWybOb58RRxsTZY9oQAtlW2mjssq6ooT/vitcAlbJNRmmMS
        Z3Y4ECwNHlinkLsBRHPlHZ8GyTwGhXxqpADezhNxKIGE8b+wChf8UsmjSEhoFFbs
        huJYvt1eojAcfbBVDXnj2wz4RrWiFzbwTwdqPmRmL4kWLW4V+ulVgx5ESbPwMsi4
        +/QbH3/Rg6cq15zNEogocG9+pP0m6FCqG0KczTL+m1yWClfZe9fv9RFWljvaC8en
        PwIDAQAB
        -----END PUBLIC KEY-----
