type: internal_cloud

environment:
  type: internal

# === Not about secrets
# You may store various secrets used in config in YAV
# To use such secrets you need to set yav token
# Get it here https://oauth.yandex-team.ru/authorize?response_type=token&client_id=ce68fbebc76c4ffda974049083729982
yav_token:
  type: empty

# === Network address to communicate with controlplane
control_plane_api:
  endpoint: localhost:8787
  plaintext: true
bypass_runner_main: true

# Y.Cloud integration
# Get YC token here https://oauth.yandex-team.ru/authorize?response_type=token&client_id=8cdb2f6a0dca48398c6880312ee2f78d
cloud_creds:
  type: passport_oauth_token
  token:
    type: environment_variable
    variable_name: YC_TOKEN
# The same as above, but used specifically for MDB requests
mdb_token:
  type: environment_variable
  variable_name: YC_TOKEN
mdb_api_url_base: https://gw.db.yandex-team.ru/
iam_api_url_base: https://gw.db.yandex-team.ru:443/iam/v1/
cloud_api_endpoint: gw.db.yandex-team.ru:443
root_cert_paths:
  - /usr/local/share/ca-certificates/YandexInternalRootCA.crt
dataplane_token:
  type: environment_variable
  variable_name: YC_TOKEN

# Connector-specific settings and other similar stuff
pg_dump_command: ["/usr/bin/pg_dump"] # pg_dump is used in pg->pg transfers to extract schema from source DB
# Some connectors use YDB to store progress
ydb_token:
  type: empty
ydb_instance: ydb-ru-prestable.yandex.net:2135
ydb_tracker_database: /ru-prestable/home/tserakhau/mydb
clickhouse_local: "clickhouse" # For clickhouse SQL transformer

# === YT runtime settings, not used if local runtime is used (default)
yt_token: # the same token is used for YT dst
  type: empty
yt_proxy: vanga
udf_dir: ./

# === Logs-related settings
log:
  type: stdout
profiler:  # Enable to send profiling samples to LB topic (useless for local environment)
  type: disabled
# You need this token if you are willing to send anything (logs/metering/search items/etc) to LB topics.
# NOTE: the same token may be used in transfers from/to LB topics, but it is recommended to set the token in the endpoint settings
logbroker_token:
  type: empty

# === Monitoring metrics settings
solomon_token:
  type: empty
solomon_cluster: rtc-local

# === Send telemetry for cloud billing
metering:
  type: disabled

# === Logfeller integration (не надо вскрывать эту тему)
logfeller_yt_token:
  type: empty
logfeller_nirvactor_token:
  type: empty
logfeller_logbroker_token:
  type: empty
logfeller_lf_describer_logbroker_token:
  type: empty
