type: external_cloud

# Common
environment:
  type: yc
control_plane_api:
  endpoint: datatransfer.private-api.yacloudkz.tech:443
  plaintext: false
log:
  type: logbroker
  endpoint: lb.ahid59uhdmk1n56tdq09.ydb.yacloudkz.tech
  creds:
    type: use_cloud_creds
  database: /kz_global/yc.data-transfer/ahi19u84sik376jdnvlm
  topic: /kz_global/yc.data-transfer/ahi19u84sik376jdnvlm/data-plane-log
  tls_mode:
    type: enabled
    ca_certificate_paths:
      - /usr/local/share/ca-certificates/YCKZInternalRootCA.crt
  use_topic_api: false
profiler:
  type: disabled
pg_dump_command: ["/usr/bin/pg_dump"]
clickhouse_local: "clickhouse"
metering:
  type: enabled
  fatal_on_error: false
  writers:
    -
      writer:
        type: logbroker
        endpoint: lb.ahid59uhdmk1n56tdq09.ydb.yacloudkz.tech
        port: 2135
        creds:
          type: use_cloud_creds
        database: /kz_global/yc.data-transfer/ahi19u84sik376jdnvlm
        tls_mode:
          type: enabled
          ca_certificate_paths:
            - /usr/local/share/ca-certificates/YCKZInternalRootCA.crt
      metrics:
        analytics: /kz_global/yc.data-transfer/ahi19u84sik376jdnvlm/analytics_metrics

# Cloud
cloud_creds:
  type: instance_metadata
root_cert_paths:
  - /usr/local/share/ca-certificates/YCKZInternalRootCA.crt
mdb_api_url_base: https://mdb.api.yandexcloud.kz/
cloud_api_endpoint: api.yandexcloud.kz:443

# External cloud
service_cloud_id: yc.data-transfer
service_folder_id: ao7p33vbaatr5ar4ls8b # Data plane
solomon_url: https://solomon.yacloudkz.tech
cloud_functions_base_url: https://functions.api.yandexcloud.kz
kms_key_id: apdtc557a3tm4ku59v5p
kms_discovery_endpoint: dpl.kms.private-api.yacloudkz.tech:8443
yds_serverless_endpoint: lb.ahid59uhdmk1n56tdq09.ydb.yacloudkz.tech # https://logbroker.yandex-team.ru/docs/concepts/clusters_and_installations#installations
metrika:
  type: disabled # Metrika source is disabled in KZ grants
