type: external_cloud

# Common
environment:
  type: yc
control_plane_api:
  endpoint: data-transfer.private-api.ycp.cloud.yandex.net:443
  plaintext: false
log:
  type: logbroker
  endpoint: lb.etn03iai600jur7pipla.ydb.mdb.yandexcloud.net
  creds:
    type: use_cloud_creds
  database: /global/b1gvcqr959dbmi1jltep/etn03iai600jur7pipla
  topic: b1g9jhnga9ji23ii4dks/data-transfer/log
  tls_mode:
    type: enabled
    ca_certificate_paths:
      - /usr/local/share/ca-certificates/YandexInternalRootCA.crt
  use_topic_api: false
profiler:
  type: disabled
pg_dump_command: ["/usr/bin/pg_dump"]
clickhouse_local: "clickhouse"
metering:
  type: enabled
  fatal_on_error: false
  writers:
    -
      writer:
        type: logbroker
        endpoint: lb.etn03iai600jur7pipla.ydb.mdb.yandexcloud.net
        port: 2135
        creds:
          type: use_cloud_creds
        database: /global/b1gvcqr959dbmi1jltep/etn03iai600jur7pipla
        tls_mode:
          type: enabled
          ca_certificate_paths:
            - /usr/local/share/ca-certificates/YandexInternalRootCA.crt
      metrics:
        analytics: b1g9jhnga9ji23ii4dks/data-transfer/analytics_metrics
        datatransfer.rows.v1: yc.billing.service-cloud/billing-datatransfer-rows-metrics
        datatransfer.runtime.cpu.v1: yc.billing.service-cloud/billing-datatransfer-cpu-runtime-metrics
        datatransfer.runtime.ram.v1: yc.billing.service-cloud/billing-datatransfer-ram-runtime-metrics

# Cloud
cloud_creds:
  type: instance_metadata
root_cert_paths:
  - /usr/local/share/ca-certificates/YandexInternalRootCA.crt
mdb_api_url_base: https://mdb.api.cloud.yandex.net/
cloud_api_endpoint: api.cloud.yandex.net:443

# External cloud
service_cloud_id: b1g9jhnga9ji23ii4dks
service_folder_id: b1gds2039chq7kv8pmvv
solomon_url: https://solomon.cloud.yandex-team.ru
cloud_functions_base_url: https://functions.yandexcloud.net
kms_key_id: abjvp62i676fpehfd3vj
kms_discovery_endpoint: kms.yandex:8443
yds_serverless_endpoint: yds.serverless.yandexcloud.net
metrika:
  type: enabled
  api:
    endpoint: internalapi.metrika.yandex.net
    tvm_metrika_id: 2000270
    tvm_self_id: 2038889
    tvm_secret:
      type: kms
      ciphertext: !!binary |
        AAAAAQAAABRhYmo4bHBnMGhwYjRyOWo5cDlkbgAAABAoofCTpx29gJknk38dGA8MAAAADAFr6+HCQyVDnIj6KelYHW8KSuSn3V3EGeO6hzK2QUnGFjfmBZcWxZjqV9HgpzBAdMng2w==
  topics:
    endpoint: lb.etnu38bg263v8rqsj58n.ydb.mdb.yandexcloud.net:2135
    database: /global/b1g5mv5j313nt9j9irv2/etnu38bg263v8rqsj58n
    iam_token_service_api: iam.api.cloud.yandex.net:443
    creds:
      type: service_account_key
      id: ajeb9jne7injbmg15ivv
      service_account_id: ajeeckiq5i4biq9h17d0
      key_algorithm: RSA_2048
      private_key:
        type: kms
        ciphertext: !!binary |
          AAAAAQAAABRhYmo4bHBnMGhwYjRyOWo5cDlkbgAAABDd+QeQf7UkkrifZAzezXp0AAAADNMiznPZKvI6m73I4WYZw8tGfvHKvAcLhSfJ1zeebqc8Ew77JB43Wp9RPDnS4JiToQ41zb4zB9Ckd3dLiDYJo+G4sqp+VnKy0pjr3WXIWrziV2kqfXAeAiIYNTeElvINjsTb6OuqQyotl2YkJ0tYSnsq57U5OaCmBN+DFzrbzR0S+c4UkIshpojm7H8iZ778SaFJlFbRZHzhIHi/lKuHXoM6Aoxd4o4l66ydGh1FeHSyPalQ2Bik/jvrPui4cmEjSpj1j+vEaTfNaLIb1xX7/XNXNCCxFqmmB6ce09vT6gozzR4HT7wZlB96NJZpfu3iztTUMnGCACOX3MFrd6v7DQwpkNRFHF/SVkhGcelosI2XGrZ/EnG96qjb6iI98HHMdYDy7plfXORpch9Whkptpv1PhU0nd4PVwwA40Ml0B0Z7g4Liwi4KXgjEKnRokVZbLRcDcrmQxkrvANuw009AYoRJngDXZ3PY6CtgKISLYnSL6nIWcmvSb2CeqowfGjLMd9Bzv/jbrclZOMBDh8WIJW/1vueZG1FzAGLpVNm5nxYIqFFdbo32kVB0WBOCs1g1/Cv/vvgRVF3NL6DCqiJNkeBY8ZhoibdHDoLhS7ulOT+OWzl6zWUEkI1T02KEiG6C878bvagr5KcLIw+jqfJOcorbr9kRr1zoBXOt/RWRimQ5UtyJFRTSk53KmxbJ7IjcI02G1XcqVI6lRn8Vv02Ilc5J59YlYjjJ3acbvR3xwg/N+Y4BUxPaTaEkbxfTvUHI9qaX/d25VChceLZKh5Ed8zv2Ao5tp6yzdEZs4NBOgFM2Gf4QLdgTeGE+t0O9pprSb5KtY4UEKvsj8lHsXMYMaMsuyTgO27qoyXYbB+bW0Rw79zAKekv5qc3A8C9qBbiP2KCIpNMgdCZfpJEI91jJMbHTrEUr9QP/Mq1RGA2Bo3QMvp5E7mRlAxNnhDi657iayUHPBd7lKLIWCPbNuAqBi4N5BaAg+EH0G2d2LYUtaiinrkX65o7jZHR3duSepIwDOE19TIAwsZlqUQ4x2BNBBxnzjG1IEb+W9YDhgaNAkiq475RBPr4v2dO1rUnAplUuGFhwWYfoagXhsv078NTXHpYZEAYrGynWwEP8cEexHyWaKlTOJhGp3nnS0VQvP0RF1yLe4853DJdGOr4iKYHrDMD+HjbmeZekEsuy4PRTV4SwxzvJ8BeaCK2pTsX+JyX4sowyQvtAQf5mk6m6yHQoOs+UxVRnBVkqnGv6gnfcvM1b4hbT6bXljo3deGwYU+v0YtHBnR6g7t0wPzkHdZqW2K+UWbiSDIxs9R39px9hZphGzuyRCswwZntp/b7+il/gjQBKiJpJs2UkvoXsfpbilkEVu0QF8XoY4IPC3PE/PFMXHa3HFL94itvdxHIArcjEYLRHeYCAmPZFPuNozrawVk97dAoXD8WJIaUZ+/VdC6M0JH7aGIsaWFNiJy724IJTXWvfMCR6/bGD3ogBcXBCAqR36DeHpRDJHP83dyV0E9yCz/a9kGbQIvwbMBOZr9RCSJUov2L9YBi/vx37MErzRUVMV/aCSFtt1JvuiwFl8/fV5WYOpmtsuTpuBvhx1EdyjIfr3jPV8EhaZ6lVZz7291GZFhSpQwf+2J0AdX06yZTyuNEjb0XlOH+TUDZMFjxPg1S58L7I6RVW0BQZva8LvwECRXBM9odvZrWe0i2X1VguNjROGTabStoC1wj0TT7EvjTO6hH/VrpM+XNd0FGFUbXTwYqI+xjSiACafr4n1S4KVNZ2DMIKaA92BRyU21WqI2RQUtLcHZStQ2OfplvrtGjDDZAtmlniExryz0HSOKbcnErjWZ1aZR96+yZSN3ULyUs3DwLCMhAchwyi30btLW8Wr8N1uM1YbO9QXawGgmHxol7y8sbhZYbpO77LwAJuDjrpduTWWExk2FAy3vzJpO9Cuiv7/EYPaxYk+u8mNzljo+gEFdybXWedBtFIE0Psq1yNJHKXRAXjqBpqKlExUlZEUlWl2nAl9ePW0gD1q0McHR84zTmF+ffo+LjSLHoI9rtvly4sgzGzcCqF0doPOIiQqxyl/0bHO96P4PIMjjylGhomv705Q+6Mq34TEitkK6yQgQtOi3IZdOfQtl0/ijO0PpDrWaahjGtEg8ICPRL/rLtpWPeRtV8k3gKtcE1gF1zBLcxYrVH7DDvoaINLxjOEqfUGQpLc069VdcFdvTNiwEGF61B4Xd/gQJs+6Fm3cwekjbZ1e+1DNf6tLCpGwrN5ukvpQBHFGEwXivH8z2XYr+fL0LGPAQbGdXcaxEZIDgRZdaLO
      public_key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlkh2SEI0GOG0Hx+ATEA/
        w3/zfHLEDSfsQ7PoR9kzCOZgSOBArHx9ERlG/m97+PCdNXCDb9oVHhIy4J7It7WS
        +l9t5rbnXKrz9cZe52jBy8O9hgOUKDeiFpK529fd9RihE0gxoODC/mFxr2xtU/3w
        NVJSX51ai1PRn+zV2PUDNe8muQk7b746w5JMGlggYL+2giKJOL0rJHIU+KY6A4Bb
        aP+GslYLnK1oktcoDsr2Dexspx4Zb/9KUppyi/d4IsBurKV+PQek2F06zPfW6OPL
        SSeXHdEsW3vxnrONzxp5b3sz3W9rLhW8UrwoEOzdlk33tEPmIy7wSX3d9YB3tz+x
        GwIDAQAB
        -----END PUBLIC KEY-----
