type: external_cloud

# Common
environment:
  type: nebius
control_plane_api:
  endpoint: datatransfer.private-api.yandexcloud.co.il:443
  plaintext: false
log:
  type: logbroker
  endpoint: lb.tm7unn71h7i7cn31d.ydb.yandexcloud.co.il:2135
  creds:
    type: use_cloud_creds
  database: /israel_global/b48rrrssu9g9bdfco0ig/6umhdiqskd3g9eb2v
  topic: /israel_global/b48rrrssu9g9bdfco0ig/6umhdiqskd3g9eb2v/data-plane-log
  tls_mode:
    type: enabled
    ca_certificate_paths:
      - /usr/local/share/ca-certificates/NebiusILInternalRootCA.crt
  use_topic_api: true
profiler:
  type: disabled
pg_dump_command: ["/usr/bin/pg_dump"]
clickhouse_local: "clickhouse"
metering:
  type: disabled

# Cloud
cloud_creds:
  type: instance_metadata
root_cert_paths:
  - /usr/local/share/ca-certificates/NebiusILInternalRootCA.crt
mdb_api_url_base: https://mdb.api.il.nebius.cloud/
cloud_api_endpoint: api.il.nebius.cloud:443

# External cloud
service_cloud_id: b48rrrssu9g9bdfco0ig
service_folder_id: b483ncnb5ehmtfbmrjsv
solomon_url: https://solomon.yandexcloud.co.il
cloud_functions_base_url: "" # TODO
kms_key_id: c424j011egpi5bbl89l2
kms_discovery_endpoint: dpl.kms.private-api.yandexcloud.co.il:8443
yds_serverless_endpoint: "" # TODO
metrika:
  type: disabled
