apiVersion: batch/v1
kind: CronJob
metadata:
  name: transfer-{{ .Values.transferSpec.id }}-adhoc
spec:
  suspend: {{.Values.transferSpec.regular_snapshot.enabled}}
  schedule: {{.Values.transferSpec.regular_snapshot.cron_expression}}
  jobTemplate:
    spec:
      completions: {{ .Values.snapshot.worker_count }}
      parallelism: {{ .Values.snapshot.worker_count }}
      completionMode: Indexed
      backoffLimit: 6
      template:
        metadata:
          annotations:
            prometheus.io/path: /metrics
            prometheus.io/port: '9091'
            prometheus.io/scrape: 'true'
        spec:
          restartPolicy: Never
        {{- include "transfer.spec" (dict "commandType" "activate" "Values" .Values) | nindent 10 }}

