apiVersion: batch/v1
kind: Job
metadata:
  name: transfer-{{ .Values.transferSpec.id }}-snapshot
spec:
  completions: {{ .Values.snapshot.worker_count }}
  parallelism: {{ .Values.snapshot.worker_count }}
  completionMode: Indexed
  backoffLimit: 6
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '9091'
        prometheus.io/scrape: 'true'
    spec:
      restartPolicy: Never
    {{- include "transfer.spec" (dict "commandType" "activate" "Values" .Values) | nindent 6 }}
