{{- if or (eq .Values.transferSpec.type "SNAPSHOT_ONLY") (eq .Values.transferSpec.type "SNAPSHOT_AND_INCREMENT") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: transfer-{{ .Values.transferSpec.id }}-snapshot
spec:
  completions: {{ .Values.snapshot.worker_count }}
  parallelism: {{ .Values.snapshot.worker_count }}
  completionMode: Indexed
  backoffLimit: 6
  template:
    spec:
      containers:
        - name: transfer
          image: {{ .Values.image }}
          command: ["/usr/local/bin/trcli", "activate", "--transfer", "/var/config/config.yaml"]
          volumeMounts:
            - name: config-volume
              mountPath: /var/config/config.yaml
              subPath: config.yaml
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: transfer-{{ .Values.transferSpec.id }}-config
            items:
              - key: config.yaml
                path: config.yaml
{{- end }}
