{{- if or (eq .Values.transferSpec.type "INCREMENT_ONLY") (eq .Values.transferSpec.type "SNAPSHOT_AND_INCREMENT") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-upload-statefulset
spec:
  serviceName: transfer-{{ .Values.transferSpec.id }}-replication
  replicas: {{ .Values.replication.worker_count }}
  template:
    spec:
      containers:
        - name: transfer
          image: {{ .Values.image }}
          command: ["/usr/local/bin/trcli", "replication", "--transfer", "/var/config/config.yaml"]
          volumeMounts:
            - name: config-volume
              mountPath: /var/config/config.yaml
              subPath: config.yaml
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
      volumes:
        - name: config-volume
          configMap:
            name: transfer-{{ .Values.transferSpec.id }}-config
{{- end }}
