name: Merge main -> release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> release
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
