name: Versioning

on:
  pull_request:
    types:
      - closed
    branches:
      - release
  push:
    branches:
      - release
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pull-requests: write

concurrency:
  group: versioning
  cancel-in-progress: false

jobs:
  versioning:
    runs-on: ubuntu-latest

    outputs:
      current-tag: ${{ steps.calculate-version.outputs.version-string }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: release
          create_tag: true
          tag_prefix: "v"

  post-comment:
    needs: [versioning]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Comment PR"
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            **🎉 New Version Tag Created! 🎉**

            We've successfully merged your changes, and a new version has been tagged. Here are the details:

            - **Tag:** [v${{ jobs.versioning.outputs.current-tag}}](${{ github.server_url }}/${{ github.repository }}/tree/v${{ jobs.versioning.outputs.current-tag}})
            - **Repository:** [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})

            You can now proceed to create a release by visiting the [release workflow](${{ github.server_url }}/${{ github.repository }}/actions/workflows/release.yml). Click the link to get started!

            Thank you for your contribution and helping us improve. 🚀
