name: Versioning

on:
  push:
    branches:
      - release

permissions:
  contents: write
  packages: write

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      current-tag: ${{ steps.calculate-version.outputs.version-string }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: release
          create_tag: true
          tag_prefix: "v"
  release:
    needs: [versioning]
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      current-tag: ${{ needs.versioning.outputs.current-tag }}
